### ISSUE TITLE
abort() in gamescope::CWaylandInputThread::ThreadFunc

### ISSUE THREAD

**Issue by ninja-** [ValveSoftware/gamescope#1533]
I can reproduce this every time by following the steps on 3.15.9 with game Stray
 
Launch options:
```
ENABLE_GAMESCOPE_WSI=1 DXVK_HDR=1 ENABLE_HDR_WSI=1 gamescope  --force-grab-cursor  -W 3840 -H 2160 -r 240 --hdr-enabled --expose-wayland --hdr-debug-force-output -f -e --mangoapp -- %command%
```
(monitor is native 4k)

Change resolution in the game to 1920x1080.
Crash

```
#0  0x00007fdce0dabf24 in __pthread_kill_implementation () at /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fdce0d5308e in raise () at /usr/lib/x86_64-linux-gnu/libc.so.6
#2  0x00007fdce0d3a882 in abort () at /usr/lib/x86_64-linux-gnu/libc.so.6
#3  0x000055ab22a45f8f in gamescope::CWaylandInputThread::ThreadFunc (this=0x55ab393da150) at ../src/Backends/WaylandBackend.cpp:2358
#4  0x00007fdce10f69f4 in execute_native_thread_routine () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fdce0da9f5d in start_thread () at /usr/lib/x86_64-linux-gnu/libc.so.6
#6  0x00007fdce0e2ea94 in clone () at /usr/lib/x86_64-linux-gnu/libc.so.6
```

https://github.com/ValveSoftware/gamescope/blob/master/src/Backends/WaylandBackend.cpp#L2361

there are no logs of any kind before the crash happens, it's the first message after resolution change

**Comment by ninja-** [comment]
oops, looks like already reported as 1456

**Comment by ninja-** [comment]
as #1456
