### ISSUE TITLE
White screen in Vampire Survivors

### ISSUE THREAD

**Issue by gdonval** [ValveSoftware/gamescope#748]
I get a **white screen in a window instead of seeing the game** and no sound is emitted when launching *Vampire Survivors* in Steam (the commented part at the end is to bypass Steam's launcher magic):

    gamescope -r 30 -- ./VampireSurvivors --no-sandbox # %command%

I have tried multiple normal/debug flags (disable layers, sync X11, force composition, disable xres, fullscreen, borderless, windowed, xwayland count == 1 and 3, steam integration, ready fd), to no avail.

NB: The following command (no Gamescope) **does work**:

    ./VampireSurvivors --no-sandbox # %command%

NB: Vampire Survivors is an Electron-based game.

-----

Here are the logs I got from Steam, starting with a convenient diff of gamescope (`gamescope -r 30 -- ./VampireSurvivors --no-sandbox # %command%`) vs non-gamescope (`./VampireSurvivors --no-sandbox # %command%`) outputs. 

<details>
 <summary>Diff of output with and without Gamescope</summary>

```raw
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
wlserver: [backend/headless/backend.c:68] Creating headless backend
vulkan: selecting physical device 'AMD Radeon RX 5700 XT (RADV NAVI10)': queue family 1
vulkan: physical device supports DRM format modifiers
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan:   0x3231564E
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:16] Starting headless backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X1: Address already in use
wlserver: [xwayland/server.c:108] Starting Xwayland on :2
wlserver: [types/wlr_compositor.c:681] New wlr_surface 0x55b0f61504f0 (res 0x55b0f61c6a70)
wlserver: [xwayland/server.c:273] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 67
pipewire: renegotiating stream params (size: 1280x720)
wlserver: [types/wlr_compositor.c:681] New wlr_surface 0x55b0f5e82470 (res 0x55b0f5bb3e60)
wlserver: [types/wlr_compositor.c:681] New wlr_surface 0x55b0f61c3fd0 (res 0x55b0f6178700)
wlserver: surf->wl_id already set, was 11, set 18

``` 

</details>

<details>
 <summary>Total output **with** Gamescope (until game window is displayed)</summary>

```raw
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
GameAction [AppID 1794680, ActionID 32] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 1794680, ActionID 32] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 1794680, ActionID 32] : LaunchApp changed task to SynchronizingControllerConfig with ""
GameAction [AppID 1794680, ActionID 32] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 1794680, ActionID 32] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 1794680, ActionID 32] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 1794680, ActionID 32] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0gamescope  -r 30 -- ./VampireSurvivors --no-sandbox # /home/gdonval/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1794680 -- /home/gdonval/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors/launcher.sh'\0
Game process added : AppID 1794680 "gamescope  -r 30 -- ./VampireSurvivors --no-sandbox # /home/gdonval/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1794680 -- /home/gdonval/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors/launcher.sh'", ProcID 16289, IP 0.0.0.0:0
chdir /home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors
ERROR: ld.so: object '/home/gdonval/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 1794680, ActionID 32] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/gdonval/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
wlserver: [backend/headless/backend.c:68] Creating headless backend
GameAction [AppID 1794680, ActionID 32] : LaunchApp changed task to Completed with ""
vulkan: selecting physical device 'AMD Radeon RX 5700 XT (RADV NAVI10)': queue family 1
vulkan: physical device supports DRM format modifiers
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  20 (X_GetProperty)
Resource id in failed request:  0x800feb
Serial number of failed request:  21
xerror_handler: X failed, continuing
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan:   0x3231564E
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:16] Starting headless backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X1: Address already in use
wlserver: [xwayland/server.c:108] Starting Xwayland on :2
ERROR: ld.so: object '/home/gdonval/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/gdonval/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/gdonval/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
wlserver: [types/wlr_compositor.c:681] New wlr_surface 0x556083a2d6e0 (res 0x556083a967e0)
wlserver: [xwayland/server.c:273] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 67
pipewire: renegotiating stream params (size: 1280x720)
wlserver: [types/wlr_compositor.c:681] New wlr_surface 0x556083bf8a60 (res 0x556083d86f10)
Error: Cannot find module 'xapi'
    at /home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors/resources/app/.webpack/main/index.js:1:92097
    at _0x1c2971 (/home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors/resources/app/.webpack/main/index.js:1:92186)
    at App._0x98e66 (/home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors/resources/app/.webpack/main/index.js:1:90137)
    at App.emit (node:events:394:28) {
  code: 'MODULE_NOT_FOUND'
}
Error: Cannot find module 'stove'
    at /home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors/resources/app/.webpack/main/index.js:1:92339
    at _0x1c2971 (/home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors/resources/app/.webpack/main/index.js:1:92428)
    at App._0x98e66 (/home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors/resources/app/.webpack/main/index.js:1:90137)
    at App.emit (node:events:394:28) {
  code: 'MODULE_NOT_FOUND'
}
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[16341:0115/142609.366609:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
wlserver: [types/wlr_compositor.c:681] New wlr_surface 0x556083d18680 (res 0x556083d85ca0)
wlserver: surf->wl_id already set, was 11, set 19
[S_API] SteamAPI_Init(): Loaded '/home/gdonval/.local/share/Steam/linux64/steamclient.so' OK.
Game process updated : AppID 1794680 "gamescope  -r 30 -- ./VampireSurvivors --no-sandbox # /home/gdonval/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1794680 -- /home/gdonval/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors/launcher.sh'", ProcID 16307, IP 0.0.0.0:0
Setting breakpad minidump AppID = 1794680
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561199032207079 [API loaded no]

``` 

</details>

<details>
 <summary>Total output **withOUT** Gamescope (until game window is displayed)</summary>

```raw

Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
GameAction [AppID 1794680, ActionID 33] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 1794680, ActionID 33] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 1794680, ActionID 33] : LaunchApp changed task to SynchronizingControllerConfig with ""
GameAction [AppID 1794680, ActionID 33] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 1794680, ActionID 33] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 1794680, ActionID 33] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 1794680, ActionID 33] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0./VampireSurvivors --no-sandbox # /home/gdonval/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1794680 -- /home/gdonval/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors/launcher.sh'\0
Game process added : AppID 1794680 "./VampireSurvivors --no-sandbox # /home/gdonval/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1794680 -- /home/gdonval/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors/launcher.sh'", ProcID 16477, IP 0.0.0.0:0
chdir /home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors
ERROR: ld.so: object '/home/gdonval/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 1794680, ActionID 33] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/gdonval/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/gdonval/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/gdonval/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 1794680, ActionID 33] : LaunchApp changed task to Completed with ""
Gtk-Message: 14:27:35.501: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:27:35.502: Failed to load module "canberra-gtk-module"
Error: Cannot find module 'xapi'
    at /home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors/resources/app/.webpack/main/index.js:1:92097
    at _0x1c2971 (/home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors/resources/app/.webpack/main/index.js:1:92186)
    at App._0x98e66 (/home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors/resources/app/.webpack/main/index.js:1:90137)
    at App.emit (node:events:394:28) {
  code: 'MODULE_NOT_FOUND'
}
Error: Cannot find module 'stove'
    at /home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors/resources/app/.webpack/main/index.js:1:92339
    at _0x1c2971 (/home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors/resources/app/.webpack/main/index.js:1:92428)
    at App._0x98e66 (/home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors/resources/app/.webpack/main/index.js:1:90137)
    at App.emit (node:events:394:28) {
  code: 'MODULE_NOT_FOUND'
}
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[16504:0115/142735.568965:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[S_API] SteamAPI_Init(): Loaded '/home/gdonval/.local/share/Steam/linux64/steamclient.so' OK.
Game process updated : AppID 1794680 "./VampireSurvivors --no-sandbox # /home/gdonval/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1794680 -- /home/gdonval/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/gdonval/Games/SteamLibrary/steamapps/common/Vampire Survivors/launcher.sh'", ProcID 16477, IP 0.0.0.0:0
Setting breakpad minidump AppID = 1794680
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561199032207079 [API loaded no]

``` 

</details>

----

Lastly, using Steam integration (i.e. `gamescope -e`) results in nothing at all being displayed and no sound being output. Steam overlay is not active.

**Comment by Bug23451** [comment]
Can confirm the same behavior.
