### ISSUE TITLE
Streaming from the Deck on 3.5 shows blank screen and crashes when taking screenshot

### ISSUE THREAD

**Issue by safijari** [ValveSoftware/gamescope#961]
I'm on 3.5 preview. When I try to stream the Deck to my phone using the Steam Link app, or to stream a game to the Steam client on another computer, I encounter two issues
1. The stream never starts. Steam Link is just blank and streaming to the steam client shows the Deck loading screen but with no animation
2. If during this time I take a screenshot on the Deck, the Deck straight up crashes. The screen goes blank, then In get verifying installation for a bit and then I get back to the home page.

I discovered this issue when I tried taking a screenshot while I was recording the screen using gstreamer and pipewiresrc.

**Comment by safijari** [comment]
The confusing thing is that @parkerleed had it working in 3.5 after #900 was resolved but that was before 3.5 hit preview. Unsure what changed between the two builds.

**Comment by safijari** [comment]
https://github.com/ValveSoftware/gamescope/assets/5191844/bff3e0f8-3b0c-4ee0-9b5b-63a1ff9e823d

@parkerleed 's testing with the crash at the end. In his case he's on 3.6 and the streaming works but looks a bit garbled.

**Comment by parkerlreed** [comment]
Garbled was a Flatpak issue. Not anything related to being on 3.5/3.6

**Comment by safijari** [comment]
Still happening as of the update on October 5.

**Comment by safijari** [comment]
```
(deck@steamdeck ~)$ coredumpctl
TIME                          PID  UID  GID SIG     COREFILE     >
Thu 2023-11-02 18:21:40 CDT 22774 1000 1000 SIGSEGV inaccessible >
Thu 2023-11-02 18:27:26 CDT   989 1000 1000 SIGABRT inaccessible >
Thu 2023-11-02 19:29:03 CDT 10227 1000 1000 SIGABRT inaccessible >
(deck@steamdeck ~)$ coredumpctl gdb 10227
           PID: 10227 (gamescope-wl)
           UID: 1000 (deck)
           GID: 1000 (deck)
        Signal: 6 (ABRT)
     Timestamp: Thu 2023-11-02 19:29:02 CDT (19s ago)
  Command Line: gamescope --generate-drm-mode fixed --xwayland-count 2 -w 1280 -h 800 --default-touch-mode 4 --hide-cursor-delay 3000 --max-scale 2 --fade-out-duration 200 -e -R /run/user/1000/gamescope.qsXIQs6/startup.socket -T /run/user/1000/gamescope.qsXIQs6/stats.pipe -O $'*,eDP-1' --cursor-hotspot 5,3 --cursor /usr/share/steamos/steamos-cursor.png
    Executable: /usr/bin/gamescope
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/gamescope-session.service
          Unit: user@1000.service
     User Unit: gamescope-session.service
         Slice: user-1000.slice
     Owner UID: 1000 (deck)
       Boot ID: d5e0e8dd0ed54127b524e5a034364ac5
    Machine ID: 130d820f1a7a4fba84ffc60b298c6b25
      Hostname: steamdeck
       Storage: /var/lib/systemd/coredump/core.gamescope-wl.1000.d5e0e8dd0ed54127b524e5a034364ac5.10227.1698971342000000.zst (inaccessible)
       Message: Process 10227 (gamescope-wl) of user 1000 dumped core.

                Stack trace of thread 10261:
                #0  0x00007f5b54b8d26c n/a (libc.so.6 + 0x8926c)
                #1  0x00007f5b54b3da08 raise (libc.so.6 + 0x39a08)
                #2  0x00007f5b54b26538 abort (libc.so.6 + 0x22538)
                #3  0x00007f5b54b2645c n/a (libc.so.6 + 0x2245c)
                #4  0x00007f5b54b363d6 __assert_fail (libc.so.6 + 0x323d6)
                #5  0x0000556ccefc85a8 n/a (gamescope + 0x5b5a8)
                #6  0x0000556ccefdf0f3 n/a (gamescope + 0x720f3)
                #7  0x00007f5b54ee1943 execute_native_thread_routine (libstdc++.so.6 + 0xe1943)
                #8  0x00007f5b54b8b44b n/a (libc.so.6 + 0x8744b)
                #9  0x00007f5b54c0ee40 n/a (libc.so.6 + 0x10ae40)

                Stack trace of thread 10260:
                #0  0x00007f5b54c5ad2a n/a (libc.so.6 + 0x156d2a)
                #1  0x0000556cceffc0d4 n/a (gamescope + 0x8f0d4)
                #2  0x0000556ccf003516 n/a (gamescope + 0x96516)
                #3  0x00007f5b54ee1943 execute_native_thread_routine (libstdc++.so.6 + 0xe1943)
                #4  0x00007f5b54b8b44b n/a (libc.so.6 + 0x8744b)
                #5  0x00007f5b54c0ee40 n/a (libc.so.6 + 0x10ae40)

                Stack trace of thread 10231:
                #0  0x00007f5b54bd39e5 clock_nanosleep (libc.so.6 + 0xcf9e5)
                #1  0x00007f5b54bd85e7 __nanosleep (libc.so.6 + 0xd45e7)
                #2  0x00007f5b53b00455 n/a (libvulkan_radeon.so + 0x100455)
                #3  0x00007f5b53c5c34c n/a (libvulkan_radeon.so + 0x25c34c)
                #4  0x00007f5b54b8b44b n/a (libc.so.6 + 0x8744b)
                #5  0x00007f5b54c0ee40 n/a (libc.so.6 + 0x10ae40)

                Stack trace of thread 10263:
                #0  0x00007f5b54bd39e5 clock_nanosleep (libc.so.6 + 0xcf9e5)
                #1  0x00007f5b54bd85e7 __nanosleep (libc.so.6 + 0xd45e7)
                #2  0x0000556ccefe0e67 n/a (gamescope + 0x73e67)
                #3  0x00007f5b54ee1943 execute_native_thread_routine (libstdc++.so.6 + 0xe1943)
                #4  0x00007f5b54b8b44b n/a (libc.so.6 + 0x8744b)
                #5  0x00007f5b54c0ee40 n/a (libc.so.6 + 0x10ae40)

                Stack trace of thread 10262:
                #0  0x00007f5b54bfd900 __open64 (libc.so.6 + 0xf9900)
                #1  0x0000556ccefb2b05 n/a (gamescope + 0x45b05)
                #2  0x00007f5b54ee1943 execute_native_thread_routine (libstdc++.so.6 + 0xe1943)
                #3  0x00007f5b54b8b44b n/a (libc.so.6 + 0x8744b)
                #4  0x00007f5b54c0ee40 n/a (libc.so.6 + 0x10ae40)

                Stack trace of thread 10259:
                #0  0x00007f5b54c0f266 epoll_wait (libc.so.6 + 0x10b266)
                #1  0x00007f5b4be25579 n/a (libspa-support.so + 0x13579)
                #2  0x00007f5b4be18be3 n/a (libspa-support.so + 0x6be3)
                #3  0x00007f5b550dc26f n/a (libpipewire-0.3.so.0 + 0x4126f)
                #4  0x00007f5b54b8b44b n/a (libc.so.6 + 0x8744b)
                #5  0x00007f5b54c0ee40 n/a (libc.so.6 + 0x10ae40)

                Stack trace of thread 10264:
                #0  0x00007f5b54b87f0e n/a (libc.so.6 + 0x83f0e)
                #1  0x00007f5b54b8a7a0 pthread_cond_wait (libc.so.6 + 0x867a0)
                #2  0x00007f5b54ed9e11 __gthread_cond_wait (libstdc++.so.6 + 0xd9e11)
                #3  0x0000556ccefb99d5 n/a (gamescope + 0x4c9d5)
                #4  0x00007f5b54ee1943 execute_native_thread_routine (libstdc++.so.6 + 0xe1943)
                #5  0x00007f5b54b8b44b n/a (libc.so.6 + 0x8744b)
                #6  0x00007f5b54c0ee40 n/a (libc.so.6 + 0x10ae40)

                Stack trace of thread 10227:
                #0  0x00007f5b54c01c0f __poll (libc.so.6 + 0xfdc0f)
                #1  0x0000556ccefd9dff n/a (gamescope + 0x6cdff)
                #2  0x0000556ccef8f0cf n/a (gamescope + 0x220cf)
                #3  0x00007f5b54b27850 n/a (libc.so.6 + 0x23850)
                #4  0x00007f5b54b2790a __libc_start_main (libc.so.6 + 0x2390a)
                #5  0x0000556ccefb0eb5 n/a (gamescope + 0x43eb5)

                Stack trace of thread 10230:
                #0  0x00007f5b54b87f0e n/a (libc.so.6 + 0x83f0e)
                #1  0x00007f5b54b8a7a0 pthread_cond_wait (libc.so.6 + 0x867a0)
                #2  0x00007f5b53c5c41e n/a (libvulkan_radeon.so + 0x25c41e)
                #3  0x00007f5b53c3998c n/a (libvulkan_radeon.so + 0x23998c)
                #4  0x00007f5b53c5c34c n/a (libvulkan_radeon.so + 0x25c34c)
                #5  0x00007f5b54b8b44b n/a (libc.so.6 + 0x8744b)
                #6  0x00007f5b54c0ee40 n/a (libc.so.6 + 0x10ae40)

                Stack trace of thread 10229:
                #0  0x00007f5b54c01c0f __poll (libc.so.6 + 0xfdc0f)
                #1  0x0000556ccefdf607 n/a (gamescope + 0x72607)
                #2  0x00007f5b54ee1943 execute_native_thread_routine (libstdc++.so.6 + 0xe1943)
                #3  0x00007f5b54b8b44b n/a (libc.so.6 + 0x8744b)
                #4  0x00007f5b54c0ee40 n/a (libc.so.6 + 0x10ae40)
                ELF object binary architecture: AMD x86-64

Failed to open /var/lib/systemd/coredump/core.gamescope-wl.1000.d5e0e8dd0ed54127b524e5a034364ac5.10227.1698971342000000.zst: Permission denied
(1)(deck@steamdeck ~)$
```

**Comment by safijari** [comment]
```
(gdb) backtrace
#0  0x00007f5b54b8d26c in  () at /usr/lib/libc.so.6
#1  0x00007f5b54b3da08 in raise () at /usr/lib/libc.so.6
#2  0x00007f5b54b26538 in abort () at /usr/lib/libc.so.6
#3  0x00007f5b54b2645c in  () at /usr/lib/libc.so.6
#4  0x00007f5b54b363d6 in  () at /usr/lib/libc.so.6
#5  0x0000556ccefc85a8 in  ()
#6  0x0000556ccefdf0f3 in  ()
#7  0x00007f5b54ee1943 in std::execute_native_thread_routine(void*) (__p=0x556cd0c6f090)
    at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:104
#8  0x00007f5b54b8b44b in  () at /usr/lib/libc.so.6
#9  0x00007f5b54c0ee40 in  () at /usr/lib/libc.so.6
(gdb)```

**Comment by safijari** [comment]
Confirmed fixed after https://github.com/ValveSoftware/gamescope/commit/10d28b9cb3818bfe4296bf7c10a49ef4e1f1e814
